org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.21.2)
neo_version=21.1.125
neo_version_range=[21.1.125,)
loader_version_range=[5,)

neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17

mod_id=template_neoforge
mod_name=Template NeoForge
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=com.nolly.mc.template_neoforge
mod_authors=Nolly
mod_description=A clean NeoForge 1.21.1 Kotlin template mod. [+ sqlite] (Server Only)

kotlinforforge_version=5.11.0
kotlin_version=2.3.0
